new gh-pages workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,4 +1,3 @@
-
 name: Build and Deploy
 
 on:
@@ -25,8 +24,16 @@ jobs:
     - name: Build project
       run: npm run build
 
+    - name: Check if dist directory exists
+      run: |
+        if [ ! -d "./dist" ]; then
+          echo "Error: ./dist directory does not exist."
+          exit 1
+        fi
+
     - name: Deploy to GitHub Pages
+      if: success()
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
-        publish_dir: ./dist 
+        publish_dir: ./dist
